# Generated by Django 6.0 on 2025-12-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_tutor",
            field=models.BooleanField(default=False),
        ),
    ]
